# Generated by Django 4.2.1 on 2023-05-14 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0003_rename_courses_course_rename_students_student'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course',
            new_name='Courses',
        ),
        migrations.RenameModel(
            old_name='Student',
            new_name='Students',
        ),
    ]
