# Generated by Django 4.2.1 on 2023-05-14 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cs', '0002_alter_courses_code_alter_students_semester'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Courses',
            new_name='Course',
        ),
        migrations.RenameModel(
            old_name='Students',
            new_name='Student',
        ),
    ]
