pipeline {
     agent any
    parameters {
        booleanParam(name:'test', defaultValue: true, description:'this paramater help you to know project name')
        choice(name: 'namespace', choices:['dev','prod','stage'], description: '' ) 
    }

    stages {
        stage('build') {
            steps {
                echo "building your app ..."
                echo "${params.namespace}"
               
            }
        }

        stage('test') {
            when {
                expression{
                    params.test== true 
                }
            }
            steps {
                echo "testing your app ..." 
            }
        }
        
        stage('deploy') {  
            steps {
                echo "your code is deployed right now ..."
                echo "this build number $BUILD_NUMBER"
            }
        }    
    }

     post {
        always { 
            echo 'job was triggered'
        }
        success {
            echo 'your app is deployed successfully'
        }
        failure {
            echo 'dyploying failure'
        }

}
}
